import { getStore } from '@netlify/blobs';
import type { Context } from '@netlify/functions';

const sampleBooks = [
  {
    id: 'book-1',
    title: 'The Alchemist',
    titleBn: 'দ্য আলকেমিস্ট',
    author: 'Paulo Coelho',
    authorBn: 'পাওলো কোয়েলহো',
    price: 250,
    originalPrice: 350,
    coverImage: '',
    category: 'novel',
    categoryBn: 'উপন্যাস',
    tags: ['fiction', 'philosophy', 'adventure'],
    tagsBn: ['কথাসাহিত্য', 'দর্শন', 'অ্যাডভেঞ্চার'],
    mainMessage: 'Follow your dreams fearlessly',
    mainMessageBn: 'নির্ভয়ে তোমার স্বপ্নকে অনুসরণ করো',
    summary: 'A story about a shepherd boy who travels from Spain to Egypt in search of treasure.',
    summaryBn: 'এটি একটি মেষপালক বালকের গল্প যে স্পেন থেকে মিশরে ধনসম্পদের সন্ধানে যাত্রা করে। সান্তিয়াগো নামের এই বালক তার স্বপ্নকে অনুসরণ করে এক অসাধারণ যাত্রায় বের হয়। পথে সে নানা মানুষের সাথে দেখা করে, প্রেমে পড়ে এবং জীবনের গভীর সত্য উপলব্ধি করে। বইটি আমাদের শেখায় যে প্রতিটি মানুষের একটি ব্যক্তিগত কিংবদন্তি আছে এবং সেই কিংবদন্তি পূরণ করাই জীবনের আসল উদ্দেশ্য।',
    keyPoints: ['Follow your personal legend', 'The universe conspires to help you', 'Love is the essence of life'],
    keyPointsBn: ['তোমার ব্যক্তিগত কিংবদন্তি অনুসরণ করো', 'মহাবিশ্ব তোমাকে সাহায্য করার জন্য ষড়যন্ত্র করে', 'ভালোবাসাই জীবনের সারমর্ম'],
    targetAudience: 'Anyone seeking inspiration and purpose in life',
    targetAudienceBn: 'যারা জীবনে অনুপ্রেরণা ও উদ্দেশ্য খুঁজছেন',
    readingTime: '৪ ঘণ্টা',
    mood: 'motivational' as const,
    moodBn: 'অনুপ্রেরণামূলক',
    quotes: [
      { text: 'When you want something, all the universe conspires in helping you to achieve it.', textBn: 'যখন তুমি কিছু চাও, সমগ্র মহাবিশ্ব তোমাকে সেটা পেতে সাহায্য করার জন্য একসাথে কাজ করে।' },
      { text: 'There is only one thing that makes a dream impossible to achieve: the fear of failure.', textBn: 'শুধু একটি জিনিসই স্বপ্নকে অসম্ভব করে তোলে: ব্যর্থতার ভয়।' },
    ],
    aboutAuthor: 'Paulo Coelho is a Brazilian lyricist and novelist.',
    aboutAuthorBn: 'পাওলো কোয়েলহো একজন ব্রাজিলীয় গীতিকার ও ঔপন্যাসিক। তিনি বিশ্বের সবচেয়ে বেশি পঠিত লেখকদের মধ্যে একজন।',
    totalReaders: 1250,
    rating: 4.5,
    ratingBreakdown: { star5: 650, star4: 380, star3: 150, star2: 50, star1: 20 },
    reviews: [],
    relatedBookIds: ['book-2', 'book-3'],
    previewPages: [
      'প্রথম অধ্যায়\n\nসান্তিয়াগো নামের এক মেষপালক বালক একটি পরিত্যক্ত গির্জায় এসে পৌঁছালো। ছাদ অনেক আগেই ভেঙে পড়েছিল, আর সেই জায়গায় একটি বিশাল গুল্মজাতীয় গাছ গজিয়ে উঠেছিল।\n\nসে তার মেষদের গির্জার দরজায় থাকতে বলল যাতে রাতে তারা বেরিয়ে না যায়। তারপর সে পুরনো দেয়ালের গায়ে কাঠের তক্তা দিয়ে দরজা আটকে দিল।',
      'বালকটি ঘুমের মধ্যে স্বপ্ন দেখছিল। সে স্বপ্নে দেখল একটি শিশু তাকে মিশরের পিরামিডের কাছে নিয়ে যাচ্ছে। শিশুটি বলল, "যদি তুমি এখানে আসো, তুমি একটি লুকানো ধন খুঁজে পাবে।"\n\nঠিক যখন শিশুটি তাকে ধনের সঠিক জায়গাটি দেখাতে যাচ্ছিল, সে ঘুম থেকে জেগে উঠল।',
      'পরদিন সকালে, সান্তিয়াগো তার মেষদের নিয়ে তারিফার শহরের দিকে রওনা হলো। সে জানত যে সেখানে একজন বণিকের মেয়ে থাকে যার সাথে সে আবার দেখা করতে চায়।\n\nহাঁটতে হাঁটতে সে ভাবতে লাগল তার স্বপ্নের কথা। এই একই স্বপ্ন সে আগেও দেখেছিল।',
      'সান্তিয়াগো এক বৃদ্ধা মহিলার কাছে গেল যিনি স্বপ্নের ব্যাখ্যা করতে পারেন। বৃদ্ধা তার স্বপ্নের কথা শুনে বলল, "তোমাকে মিশরের পিরামিডে যেতে হবে। সেখানে তুমি ধন খুঁজে পাবে।"\n\nসান্তিয়াগো হতাশ হলো। এত দূরে যাওয়া কি সম্ভব?',
      'শহরের এক বেঞ্চে বসে সান্তিয়াগো একটি বই পড়ছিল। এমন সময় এক বৃদ্ধ লোক এসে তার পাশে বসল। বৃদ্ধ বলল, "আমি সালেমের রাজা মেল্কিসেদেক। তুমি কি তোমার ব্যক্তিগত কিংবদন্তি খুঁজে পেয়েছ?"\n\nসান্তিয়াগো অবাক হয়ে বৃদ্ধের দিকে তাকাল।',
    ],
    epubKey: '',
    published: true,
    createdAt: '2024-01-15T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'book-2',
    title: 'Atomic Habits',
    titleBn: 'অ্যাটমিক হ্যাবিটস',
    author: 'James Clear',
    authorBn: 'জেমস ক্লিয়ার',
    price: 300,
    originalPrice: 400,
    coverImage: '',
    category: 'selfhelp',
    categoryBn: 'আত্মউন্নয়ন',
    tags: ['habits', 'productivity', 'self-improvement'],
    tagsBn: ['অভ্যাস', 'উৎপাদনশীলতা', 'আত্মউন্নয়ন'],
    mainMessage: 'Small habits lead to remarkable results',
    mainMessageBn: 'ছোট ছোট অভ্যাস অসাধারণ ফলাফল আনে',
    summary: 'A practical guide to building good habits and breaking bad ones.',
    summaryBn: 'ভালো অভ্যাস গড়ে তোলা এবং খারাপ অভ্যাস ভাঙার একটি ব্যবহারিক গাইড। জেমস ক্লিয়ার দেখিয়েছেন কীভাবে প্রতিদিনের ছোট ছোট পরিবর্তন সময়ের সাথে অসাধারণ ফলাফল আনতে পারে। বইটি বৈজ্ঞানিক গবেষণা ও বাস্তব উদাহরণের মাধ্যমে অভ্যাস গঠনের চারটি নিয়ম ব্যাখ্যা করে।',
    keyPoints: ['Make habits obvious', 'Make habits attractive', 'Make habits easy', 'Make habits satisfying'],
    keyPointsBn: ['অভ্যাসকে স্পষ্ট করো', 'অভ্যাসকে আকর্ষণীয় করো', 'অভ্যাসকে সহজ করো', 'অভ্যাসকে সন্তোষজনক করো'],
    targetAudience: 'Anyone wanting to build better habits',
    targetAudienceBn: 'যারা ভালো অভ্যাস গড়তে চান',
    readingTime: '৫ ঘণ্টা',
    mood: 'motivational' as const,
    moodBn: 'অনুপ্রেরণামূলক',
    quotes: [
      { text: 'You do not rise to the level of your goals. You fall to the level of your systems.', textBn: 'তুমি তোমার লক্ষ্যের উচ্চতায় উঠো না। তুমি তোমার সিস্টেমের স্তরে নেমে আসো।' },
      { text: 'Every action you take is a vote for the type of person you wish to become.', textBn: 'তুমি যে প্রতিটি পদক্ষেপ নাও সেটি তুমি যে ধরনের মানুষ হতে চাও তার জন্য একটি ভোট।' },
    ],
    aboutAuthor: 'James Clear is an author and speaker focused on habits and decision making.',
    aboutAuthorBn: 'জেমস ক্লিয়ার একজন লেখক ও বক্তা যিনি অভ্যাস, সিদ্ধান্ত গ্রহণ এবং ক্রমাগত উন্নতির উপর দৃষ্টি নিবদ্ধ করেন।',
    totalReaders: 2100,
    rating: 4.7,
    ratingBreakdown: { star5: 1200, star4: 600, star3: 200, star2: 60, star1: 40 },
    reviews: [],
    relatedBookIds: ['book-1', 'book-5'],
    previewPages: [
      'ভূমিকা\n\nআমি যখন হাইস্কুলের দ্বিতীয় বর্ষে পড়তাম, তখন একটি দুর্ঘটনা আমার জীবন বদলে দিল। একটি বেসবল ব্যাট আমার মুখে আঘাত করল। আমার নাক ভেঙে গেল, চোখের হাড় ফেটে গেল।\n\nসেই মুহূর্তে আমি জানতাম না যে এই দুর্ঘটনাই আমাকে অভ্যাসের শক্তি বুঝতে শেখাবে।',
      'অভ্যাসের শক্তি কতটা অবিশ্বাস্য তা বোঝার জন্য একটি সাধারণ উদাহরণ দেখা যাক। যদি তুমি প্রতিদিন মাত্র ১% ভালো হও, এক বছরে তুমি ৩৭ গুণ ভালো হবে। আর যদি প্রতিদিন ১% খারাপ হও, তুমি প্রায় শূন্যে নেমে আসবে।\n\nএটাই অভ্যাসের জাদু।',
      'প্রথম অধ্যায়: ছোট পরিবর্তনের আশ্চর্য শক্তি\n\nআমরা প্রায়ই মনে করি বড় সাফল্যের জন্য বড় পদক্ষেপ দরকার। কিন্তু আসলে ছোট ছোট অভ্যাসই সময়ের সাথে সবচেয়ে বড় পরিবর্তন আনে।\n\nব্রিটিশ সাইক্লিং দলের উদাহরণ দেখো। তারা প্রতিটি ক্ষেত্রে মাত্র ১% উন্নতি করেছিল।',
      'দ্বিতীয় অধ্যায়: অভ্যাস তোমার পরিচয় গঠন করে\n\nবেশিরভাগ মানুষ অভ্যাস পরিবর্তনের চেষ্টা করে ফলাফলের দিক থেকে। তারা বলে, "আমি ওজন কমাতে চাই।" কিন্তু সত্যিকারের পরিবর্তন শুরু হয় পরিচয় থেকে।\n\n"আমি একজন সুস্থ মানুষ" - এই বিশ্বাস থেকেই স্বাস্থ্যকর অভ্যাস তৈরি হয়।',
      'তৃতীয় অধ্যায়: চারটি সহজ ধাপে ভালো অভ্যাস গড়ুন\n\nযেকোনো অভ্যাস চারটি ধাপে কাজ করে:\n১. সংকেত (Cue)\n২. আকাঙ্ক্ষা (Craving)\n৩. প্রতিক্রিয়া (Response)\n৪. পুরস্কার (Reward)\n\nএই চারটি ধাপ বুঝলে তুমি যেকোনো অভ্যাস তৈরি বা ভাঙতে পারবে।',
    ],
    epubKey: '',
    published: true,
    createdAt: '2024-02-01T00:00:00Z',
    updatedAt: '2024-02-01T00:00:00Z',
  },
  {
    id: 'book-3',
    title: 'Ikigai',
    titleBn: 'ইকিগাই',
    author: 'Héctor García & Francesc Miralles',
    authorBn: 'হেক্টর গার্সিয়া ও ফ্রান্সেস্ক মিরায়েস',
    price: 200,
    originalPrice: 280,
    coverImage: '',
    category: 'selfhelp',
    categoryBn: 'আত্মউন্নয়ন',
    tags: ['philosophy', 'longevity', 'happiness'],
    tagsBn: ['দর্শন', 'দীর্ঘায়ু', 'সুখ'],
    mainMessage: 'Find your reason for being',
    mainMessageBn: 'তোমার বেঁচে থাকার কারণ খুঁজে বের করো',
    summary: 'Discover the Japanese secret to a long and happy life.',
    summaryBn: 'দীর্ঘ ও সুখী জীবনের জাপানি রহস্য আবিষ্কার করুন। ইকিগাই হলো সেই জিনিস যা আপনাকে প্রতিদিন সকালে ঘুম থেকে উঠতে অনুপ্রাণিত করে। এই বইটি ওকিনাওয়ার শতবর্ষী মানুষদের জীবনধারা অনুসন্ধান করে এবং তাদের দীর্ঘায়ুর রহস্য উন্মোচন করে।',
    keyPoints: ['Find your ikigai', 'Stay active, never retire', 'Surround yourself with good friends'],
    keyPointsBn: ['তোমার ইকিগাই খুঁজে বের করো', 'সক্রিয় থাকো, কখনো অবসর নিও না', 'ভালো বন্ধুদের সাথে থাকো'],
    targetAudience: 'People seeking purpose and fulfillment',
    targetAudienceBn: 'যারা জীবনে উদ্দেশ্য ও পূর্ণতা খুঁজছেন',
    readingTime: '৩ ঘণ্টা',
    mood: 'informative' as const,
    moodBn: 'তথ্যমূলক',
    quotes: [
      { text: 'Our ikigai is different for all of us, but one thing we have in common is that we are all searching for meaning.', textBn: 'আমাদের প্রত্যেকের ইকিগাই আলাদা, কিন্তু একটি বিষয় আমাদের সবার মধ্যে মিল - আমরা সবাই অর্থ খুঁজছি।' },
    ],
    aboutAuthor: 'Héctor García is a Spanish author and Francesc Miralles is a Catalan author.',
    aboutAuthorBn: 'হেক্টর গার্সিয়া একজন স্প্যানিশ লেখক এবং ফ্রান্সেস্ক মিরায়েস একজন কাতালান লেখক যারা জাপানি সংস্কৃতি নিয়ে গবেষণা করেন।',
    totalReaders: 890,
    rating: 4.3,
    ratingBreakdown: { star5: 400, star4: 280, star3: 130, star2: 50, star1: 30 },
    reviews: [],
    relatedBookIds: ['book-1', 'book-2'],
    previewPages: [
      'ভূমিকা: ইকিগাই কী?\n\nজাপানি ভাষায় ইকিগাই (生き甲斐) মানে হলো "বেঁচে থাকার কারণ"। এটি সেই জিনিস যা তোমাকে প্রতিদিন সকালে ঘুম থেকে উঠতে অনুপ্রাণিত করে।\n\nজাপানের ওকিনাওয়া দ্বীপে বিশ্বের সবচেয়ে বেশি শতবর্ষী মানুষ বাস করে। তাদের দীর্ঘায়ুর রহস্য কী?',
      'ওকিনাওয়ার মানুষেরা বিশ্বাস করে যে প্রত্যেকের একটি ইকিগাই আছে। এটি খুঁজে পাওয়ার জন্য ধৈর্য্য দরকার, কিন্তু একবার খুঁজে পেলে জীবন অর্থপূর্ণ হয়ে ওঠে।\n\nইকিগাই চারটি জিনিসের সংযোগস্থলে অবস্থিত:\n১. তুমি যা ভালোবাসো\n২. তুমি যাতে দক্ষ\n৩. পৃথিবীর যা দরকার\n৪. যার জন্য তোমাকে অর্থ দেওয়া হবে',
      'প্রথম অধ্যায়: ইকিগাই - জাপানি দীর্ঘায়ুর শিল্প\n\nওকিনাওয়ায় অবসর নেওয়ার কোনো ধারণা নেই। তারা সবসময় কিছু না কিছু করে। ৯০ বছরের বৃদ্ধও প্রতিদিন বাগানে কাজ করে, বন্ধুদের সাথে দেখা করে।\n\nতাদের একটি প্রবাদ আছে: "ব্যস্ত থাকো, তাহলে দীর্ঘদিন বাঁচবে।"',
      'দ্বিতীয় অধ্যায়: প্রবাহের অবস্থা\n\nমিহাই চিকসেন্টমিহাই "ফ্লো" ধারণাটি প্রবর্তন করেন। যখন তুমি কোনো কাজে এতটাই মগ্ন থাকো যে সময়ের কথা ভুলে যাও, সেটাই ফ্লো।\n\nইকিগাই এবং ফ্লো একসাথে কাজ করে।',
      'তৃতীয় অধ্যায়: শতবর্ষীদের রহস্য\n\nওকিনাওয়ার ওগিমি গ্রামকে বলা হয় "দীর্ঘায়ু গ্রাম"। এখানকার মানুষদের গড় আয়ু বিশ্বের সবচেয়ে বেশি।\n\nতাদের খাদ্যাভ্যাস, সামাজিক বন্ধন এবং জীবনের প্রতি দৃষ্টিভঙ্গি - সবকিছুই তাদের দীর্ঘায়ুতে ভূমিকা রাখে।',
    ],
    epubKey: '',
    published: true,
    createdAt: '2024-02-15T00:00:00Z',
    updatedAt: '2024-02-15T00:00:00Z',
  },
  {
    id: 'book-4',
    title: 'Stories of the Prophets',
    titleBn: 'নবীদের কাহিনী',
    author: 'Ibn Kathir',
    authorBn: 'ইবনে কাসীর',
    price: 350,
    originalPrice: 450,
    coverImage: '',
    category: 'islamic',
    categoryBn: 'ইসলামিক',
    tags: ['islam', 'prophets', 'history'],
    tagsBn: ['ইসলাম', 'নবী', 'ইতিহাস'],
    mainMessage: 'Learn from the lives of the prophets',
    mainMessageBn: 'নবীদের জীবন থেকে শিক্ষা নিন',
    summary: 'Stories of all prophets mentioned in the Quran.',
    summaryBn: 'কুরআনে উল্লেখিত সকল নবীদের কাহিনী। এই বইটি আদম (আ.) থেকে মুহাম্মদ (সা.) পর্যন্ত সকল নবীর জীবনী, তাঁদের সংগ্রাম ও শিক্ষা তুলে ধরে। ইবনে কাসীরের এই ক্লাসিক রচনা বিশ্বব্যাপী মুসলিমদের কাছে অত্যন্ত জনপ্রিয়।',
    keyPoints: ['Patience in adversity', 'Trust in Allah', 'Dedication to truth'],
    keyPointsBn: ['বিপদে ধৈর্য ধরা', 'আল্লাহর উপর ভরসা রাখা', 'সত্যের প্রতি নিষ্ঠা'],
    targetAudience: 'Muslims and anyone interested in prophetic stories',
    targetAudienceBn: 'মুসলিম এবং নবীদের কাহিনীতে আগ্রহী যে কেউ',
    readingTime: '৮ ঘণ্টা',
    mood: 'informative' as const,
    moodBn: 'তথ্যমূলক',
    quotes: [
      { text: 'Indeed, with hardship comes ease.', textBn: 'নিশ্চয়ই কষ্টের সাথে স্বস্তি আছে।' },
      { text: 'And whoever puts their trust in Allah, He will be enough for them.', textBn: 'আর যে আল্লাহর উপর তাওয়াক্কুল করে, তিনিই তার জন্য যথেষ্ট।' },
    ],
    aboutAuthor: 'Ibn Kathir was a renowned Islamic scholar and historian.',
    aboutAuthorBn: 'ইবনে কাসীর একজন বিখ্যাত ইসলামিক পণ্ডিত ও ইতিহাসবিদ ছিলেন। তাঁর তাফসীর ইবনে কাসীর বিশ্বের সবচেয়ে প্রসিদ্ধ কুরআন ব্যাখ্যাগুলোর মধ্যে একটি।',
    totalReaders: 3200,
    rating: 4.8,
    ratingBreakdown: { star5: 2000, star4: 800, star3: 250, star2: 100, star1: 50 },
    reviews: [],
    relatedBookIds: ['book-3'],
    previewPages: [
      'বিসমিল্লাহির রাহমানির রাহীম\n\nভূমিকা\n\nসমস্ত প্রশংসা আল্লাহর জন্য, যিনি মানবজাতিকে হেদায়েত দেওয়ার জন্য যুগে যুগে নবী ও রাসূল পাঠিয়েছেন।\n\nএই বইটি কুরআন ও হাদীসের আলোকে নবীদের কাহিনী বর্ণনা করে।',
      'আদম (আ.) - প্রথম মানুষ ও প্রথম নবী\n\nআল্লাহ ফেরেশতাদের বললেন, "আমি পৃথিবীতে একজন প্রতিনিধি সৃষ্টি করতে যাচ্ছি।" ফেরেশতারা বলল, "আপনি কি সেখানে এমন কাউকে সৃষ্টি করবেন যে ফাসাদ করবে?"\n\nআল্লাহ বললেন, "আমি যা জানি তোমরা তা জানো না।"',
      'আল্লাহ আদমকে মাটি থেকে সৃষ্টি করলেন এবং তাঁর মধ্যে রূহ ফুঁকে দিলেন। তারপর তিনি আদমকে সকল জিনিসের নাম শেখালেন।\n\nআল্লাহ ফেরেশতাদের বললেন, "আদমকে সিজদা করো।" সকলে সিজদা করল, কিন্তু ইবলিস অহংকার করে অস্বীকার করল।',
      'নূহ (আ.) - মহাপ্লাবনের নবী\n\nনূহ (আ.) তাঁর জাতিকে ৯৫০ বছর ধরে আল্লাহর পথে আহ্বান করেছিলেন। কিন্তু তাঁর জাতির অধিকাংশ মানুষ তাঁকে প্রত্যাখ্যান করেছিল।\n\nঅবশেষে আল্লাহ নূহকে একটি নৌকা তৈরি করতে বললেন।',
      'ইব্রাহীম (আ.) - আল্লাহর বন্ধু\n\nইব্রাহীম (আ.) ছিলেন একজন সাহসী নবী যিনি একাই তাঁর পুরো জাতির মূর্তিপূজার বিরুদ্ধে দাঁড়িয়েছিলেন।\n\nযখন তাঁকে আগুনে নিক্ষেপ করা হলো, আল্লাহ আগুনকে বললেন, "হে আগুন, ইব্রাহীমের জন্য শীতল ও নিরাপদ হয়ে যাও।"',
    ],
    epubKey: '',
    published: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'book-5',
    title: 'Rich Dad Poor Dad',
    titleBn: 'রিচ ড্যাড পুওর ড্যাড',
    author: 'Robert Kiyosaki',
    authorBn: 'রবার্ট কিয়োসাকি',
    price: 280,
    originalPrice: 380,
    coverImage: '',
    category: 'selfhelp',
    categoryBn: 'আত্মউন্নয়ন',
    tags: ['finance', 'money', 'investment'],
    tagsBn: ['অর্থনীতি', 'টাকা', 'বিনিয়োগ'],
    mainMessage: 'Make money work for you',
    mainMessageBn: 'টাকাকে তোমার জন্য কাজ করাও',
    summary: 'What the rich teach their kids about money that the poor do not.',
    summaryBn: 'ধনীরা তাদের সন্তানদের টাকা সম্পর্কে যা শেখায় যা গরিবরা শেখায় না। রবার্ট কিয়োসাকি তাঁর দুই বাবার গল্পের মাধ্যমে আর্থিক শিক্ষার গুরুত্ব তুলে ধরেন। বইটি সম্পদ তৈরি, বিনিয়োগ এবং আর্থিক স্বাধীনতার মূল নীতিগুলো শেখায়।',
    keyPoints: ['Assets vs Liabilities', 'Financial literacy is key', 'Mind your own business'],
    keyPointsBn: ['সম্পদ বনাম দায়', 'আর্থিক সাক্ষরতাই মূল', 'নিজের ব্যবসায় মনোযোগ দাও'],
    targetAudience: 'Anyone wanting financial independence',
    targetAudienceBn: 'যারা আর্থিক স্বাধীনতা চান',
    readingTime: '৫ ঘণ্টা',
    mood: 'motivational' as const,
    moodBn: 'অনুপ্রেরণামূলক',
    quotes: [
      { text: 'The poor and the middle class work for money. The rich have money work for them.', textBn: 'গরিব ও মধ্যবিত্তরা টাকার জন্য কাজ করে। ধনীরা টাকাকে তাদের জন্য কাজ করায়।' },
    ],
    aboutAuthor: 'Robert Kiyosaki is an American businessman and author.',
    aboutAuthorBn: 'রবার্ট কিয়োসাকি একজন আমেরিকান ব্যবসায়ী ও লেখক যিনি আর্থিক শিক্ষার জন্য বিশ্বব্যাপী পরিচিত।',
    totalReaders: 1800,
    rating: 4.4,
    ratingBreakdown: { star5: 900, star4: 500, star3: 250, star2: 100, star1: 50 },
    reviews: [],
    relatedBookIds: ['book-2', 'book-1'],
    previewPages: [
      'ভূমিকা\n\nআমার দুজন বাবা ছিল - একজন ধনী, একজন গরিব। একজন অত্যন্ত শিক্ষিত ছিলেন, পিএইচডি ডিগ্রি ছিল। অন্যজন অষ্টম শ্রেণির বেশি পড়েননি। দুজনেই কঠোর পরিশ্রমী ছিলেন। দুজনেই ভালো আয় করতেন।\n\nকিন্তু একজন সারাজীবন আর্থিক সমস্যায় ভুগেছেন, আর অন্যজন হাওয়াইয়ের সবচেয়ে ধনী ব্যক্তিদের একজন হয়েছেন।',
      'প্রথম অধ্যায়: ধনীরা টাকার জন্য কাজ করে না\n\nরিচ ড্যাড আমাকে প্রথম শিক্ষা দিয়েছিলেন: "গরিবরা এবং মধ্যবিত্তরা টাকার জন্য কাজ করে। ধনীরা টাকাকে তাদের জন্য কাজ করায়।"\n\nএই সহজ কিন্তু গভীর শিক্ষাটি আমার জীবন বদলে দিয়েছিল।',
      'দ্বিতীয় অধ্যায়: কেন আর্থিক সাক্ষরতা শেখানো উচিত?\n\nরিচ ড্যাড বলেছিলেন, "স্কুলে তারা তোমাকে টাকার কথা শেখায় না। তারা তোমাকে অন্যের জন্য কাজ করতে শেখায়।"\n\nসম্পদ কী এবং দায় কী - এই পার্থক্য না জানাই বেশিরভাগ মানুষের আর্থিক সমস্যার মূল কারণ।',
      'তৃতীয় অধ্যায়: নিজের ব্যবসায় মনোযোগ দাও\n\nরিচ ড্যাড বলেছিলেন, "চাকরি আর ব্যবসা এক জিনিস নয়। তোমার চাকরি হলো তোমার পেশা। কিন্তু তোমার ব্যবসা হলো তোমার সম্পদের ভিত্তি।"\n\nম্যাকডোনাল্ডসের রে ক্রকের উদাহরণ দিয়ে তিনি বুঝিয়েছিলেন যে আসল ব্যবসা হলো রিয়েল এস্টেট, হ্যামবার্গার নয়।',
      'চতুর্থ অধ্যায়: ট্যাক্স এবং কর্পোরেশনের শক্তি\n\nধনীরা কর্পোরেশন ব্যবহার করে ট্যাক্স কমায়। এটি সম্পূর্ণ আইনসিদ্ধ। পুওর ড্যাড বলতেন, "ধনীদের বেশি ট্যাক্স দেওয়া উচিত।" রিচ ড্যাড বলতেন, "ট্যাক্স আইন বোঝো এবং সেটি তোমার সুবিধায় ব্যবহার করো।"',
    ],
    epubKey: '',
    published: true,
    createdAt: '2024-03-01T00:00:00Z',
    updatedAt: '2024-03-01T00:00:00Z',
  },
  {
    id: 'book-6',
    title: 'A Brief History of Time',
    titleBn: 'কালের সংক্ষিপ্ত ইতিহাস',
    author: 'Stephen Hawking',
    authorBn: 'স্টিফেন হকিং',
    price: 320,
    originalPrice: 420,
    coverImage: '',
    category: 'science',
    categoryBn: 'বিজ্ঞান',
    tags: ['physics', 'cosmology', 'universe'],
    tagsBn: ['পদার্থবিজ্ঞান', 'মহাজাগতিক', 'মহাবিশ্ব'],
    mainMessage: 'Understanding the universe we live in',
    mainMessageBn: 'আমরা যে মহাবিশ্বে বাস করি তা বোঝা',
    summary: 'An exploration of the universe, time, and the nature of reality.',
    summaryBn: 'মহাবিশ্ব, সময় এবং বাস্তবতার প্রকৃতি নিয়ে একটি অনুসন্ধান। স্টিফেন হকিং জটিল বৈজ্ঞানিক ধারণাগুলো সাধারণ মানুষের জন্য সহজ ভাষায় ব্যাখ্যা করেছেন। বিগ ব্যাং থেকে ব্ল্যাক হোল - মহাবিশ্বের সবচেয়ে বড় রহস্যগুলো এই বইয়ে উন্মোচিত হয়েছে।',
    keyPoints: ['The Big Bang theory', 'Black holes are not completely black', 'Time is relative'],
    keyPointsBn: ['বিগ ব্যাং তত্ত্ব', 'ব্ল্যাক হোল সম্পূর্ণ কালো নয়', 'সময় আপেক্ষিক'],
    targetAudience: 'Science enthusiasts and curious minds',
    targetAudienceBn: 'বিজ্ঞান উৎসাহী এবং কৌতূহলী মন',
    readingTime: '৬ ঘণ্টা',
    mood: 'informative' as const,
    moodBn: 'তথ্যমূলক',
    quotes: [
      { text: 'Remember to look up at the stars and not down at your feet.', textBn: 'মনে রেখো তারার দিকে তাকাও, পায়ের দিকে নয়।' },
    ],
    aboutAuthor: 'Stephen Hawking was a renowned theoretical physicist.',
    aboutAuthorBn: 'স্টিফেন হকিং ছিলেন বিশ্বের সবচেয়ে বিখ্যাত তাত্ত্বিক পদার্থবিদদের একজন। তিনি কেমব্রিজ বিশ্ববিদ্যালয়ে অধ্যাপনা করেছেন।',
    totalReaders: 1500,
    rating: 4.6,
    ratingBreakdown: { star5: 800, star4: 450, star3: 150, star2: 60, star1: 40 },
    reviews: [],
    relatedBookIds: ['book-3'],
    previewPages: [
      'প্রথম অধ্যায়: মহাবিশ্বের চিত্র\n\nএকজন বিখ্যাত বিজ্ঞানী একবার জ্যোতির্বিদ্যা নিয়ে জনসাধারণের জন্য বক্তৃতা দিচ্ছিলেন। তিনি বর্ণনা করলেন কীভাবে পৃথিবী সূর্যের চারদিকে ঘোরে এবং সূর্য আমাদের ছায়াপথের কেন্দ্রের চারদিকে ঘোরে।\n\nবক্তৃতা শেষে একজন বৃদ্ধা মহিলা দাঁড়িয়ে বললেন, "আপনি বাজে কথা বলছেন! পৃথিবী আসলে একটি বিশাল কচ্ছপের পিঠে অবস্থিত!"',
      'বিজ্ঞানী হেসে জিজ্ঞেস করলেন, "তাহলে কচ্ছপটি কিসের উপর দাঁড়িয়ে আছে?"\n\nবৃদ্ধা উত্তর দিলেন, "তুমি খুব চালাক, তরুণ! কিন্তু এটি কচ্ছপের উপর কচ্ছপ - একদম নিচ পর্যন্ত!"\n\nমহাবিশ্ব সম্পর্কে আমাদের ধারণা ক্রমেই পরিবর্তিত হয়েছে।',
      'এরিস্টটল বিশ্বাস করতেন পৃথিবী স্থির এবং সূর্য, চাঁদ, গ্রহ ও তারা পৃথিবীর চারদিকে ঘোরে। ১৫৪৩ সালে কোপার্নিকাস প্রস্তাব করলেন যে সূর্য কেন্দ্রে আছে এবং পৃথিবী তার চারদিকে ঘোরে।\n\nগ্যালিলিও এই তত্ত্বকে সমর্থন করলেন এবং এর জন্য তাঁকে গৃহবন্দী করা হয়েছিল।',
      'নিউটনের মহাকর্ষ সূত্র ব্যাখ্যা করল কেন গ্রহগুলো সূর্যের চারদিকে ঘোরে। কিন্তু একটি প্রশ্ন রয়ে গেল: মহাবিশ্বের কি শুরু আছে?\n\nযদি মহাবিশ্ব অসীম হয়, তাহলে রাতের আকাশ অন্ধকার কেন? প্রতিটি দিকে তাকালে একটি না একটি তারা থাকা উচিত।',
      'বিংশ শতাব্দীতে আইনস্টাইনের সাধারণ আপেক্ষিকতা তত্ত্ব মহাবিশ্ব সম্পর্কে আমাদের ধারণা সম্পূর্ণ বদলে দিল। সময় ও স্থান আলাদা নয় - এরা একটি চার-মাত্রিক "স্থান-কাল" (spacetime) গঠন করে।\n\nভারী বস্তু স্থান-কালকে বাঁকিয়ে দেয়, এবং এই বক্রতাই আমরা মহাকর্ষ হিসেবে অনুভব করি।',
    ],
    epubKey: '',
    published: true,
    createdAt: '2024-02-20T00:00:00Z',
    updatedAt: '2024-02-20T00:00:00Z',
  },
];

export default async (req: Request, context: Context) => {
  const adminPassword = Netlify.env.get('ADMIN_PASSWORD') || 'admin123';
  const authHeader = req.headers.get('x-admin-password');
  if (authHeader !== adminPassword) {
    return new Response('Unauthorized', { status: 401 });
  }

  const store = getStore('books');
  let seeded = 0;

  for (const book of sampleBooks) {
    await store.setJSON(book.id, book);
    seeded++;
  }

  return Response.json({ success: true, seeded });
};

export const config = {
  path: '/api/seed-books',
  method: ['POST'],
};
